# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/welcome.ipynb

# New Section
%%bash

curl -s -o NAVAll.txt https://www.amfiindia.com/spages/NAVAll.txt

awk -F';' 'NR>1 && NF>=5 {print $4"\t"$5}' NAVAll.txt > scheme_nav.tsv

echo "First 10 lines of scheme_nav.tsv:"
head scheme_nav.tsv
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# 
# curl -s -o NAVAll.txt https://www.amfiindia.com/spages/NAVAll.txt
# 
# awk -F';' 'NR>1 && NF>=5 {print $4"\t"$5}' NAVAll.txt > scheme_nav.tsv
# 
# echo "First 10 lines of scheme_nav.tsv:"
# head scheme_nav.tsv
#